CREATE OR REPLACE FUNCTION
importeTransacciones(tipotrans NUMBER,fecha1 DATE, fecha2 DATE)
RETURN NUMBER AS
IMPORTETOTAL NUMBER;
BEGIN

SELECT SUM(CANTIDAD) INTO IMPORTETOTAL FROM TRANSACCION
WHERE
(
( 
TIPOTRANSACCION=tipotrans) AND
(
FECHA BETWEEN fecha1 AND fecha2
)
)
;
RETURN IMPORTETOTAL;
END;


create or replace
FUNCTION
acumBanco(tipotrans NUMBER,sucursal NUMBER)
RETURN NUMBER AS
TOTAL NUMBER;
BEGIN

SELECT SUM(CANTIDAD) INTO TOTAL FROM TRANSACCION
WHERE 
(
(TIPOTRANSACCION=tipotrans) AND
(NOSUCURSAL=sucursal)
);
RETURN TOTAL;
END;

CREATE OR REPLACE 
FUNCTION
INCNTRANS
RETURN NUMBER AS
SIGUIENTE NUMBER;
BEGIN
SELECT MAX(NOTRANSACCION) INTO SIGUIENTE FROM TRANSACCION;
RETURN SIGUIENTE+1;
END;

CREATE OR REPLACE 
FUNCTION
INCNCUENTA
RETURN NUMBER AS
SIGUIENTE NUMBER;
BEGIN
SELECT MAX(NOCUENTA) INTO SIGUIENTE FROM CUENTA;
RETURN SIGUIENTE+1;
END;