CREATE TABLE CLIENTE
(

IDCLIENTE NUMBER NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DOMICILIO VARCHAR(60) NOT NULL,
TELEFONO VARCHAR(15) NOT NULL,
FECHANAC DATE NOT NULL,
FECHAREG DATE NOT NULL,
CONSTRAINT IDCLIENTE_PK PRIMARY KEY(IDCLIENTE)
);

CREATE TABLE CUENTA
(
NOCUENTA NUMBER NOT NULL,
IDCLIENTE NUMBER NOT NULL,
TIPOCUENTE NUMBER NOT NULL,
FECHAALTA DATE NOT NULL,
FECHABAJA DATE,
SALDO NUMBER NOT NULL,
LIMCREDITO NUMBER NOT NULL,
CONSTRAINT NOCUENTA_PK PRIMARY KEY(NOCUENTA),
CONSTRAINT IDCLIENTE_FK FOREIGN KEY (IDCLIENTE) 
REFERENCES CLIENTE (IDCLIENTE)

);

CREATE TABLE SUCURSAL 
(
NOSUCURSAL NUMBER NOT NULL,
DIRECCION VARCHAR(60) NOT NULL,
LOCALIZACION VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(15),
CONSTRAINT NOSUCURSAL_PK PRIMARY KEY(NOSUCURSAL)
);

CREATE TABLE TRANSACCION
(
NOTRANSACCION NUMBER NOT NULL,
FECHA DATE NOT NULL,
CANTIDAD NUMBER NOT NULL,
TIPOTRANSACCION NUMBER NOT NULL,
NOCUENTA1 NUMBER NOT NULL,
NOCUENTA2 NUMBER,
NOSUCURSAL NUMBER NOT NULL,
CONSTRAINT NOTRANSACCION_PK PRIMARY KEY(NOTRANSACCION),
CONSTRAINT NOCUENTA1_FK FOREIGN KEY(NOCUENTA1)
REFERENCES CUENTA(NOCUENTA),
CONSTRAINT NOCUENTA2_FK FOREIGN KEY(NOCUENTA2)
REFERENCES CUENTA(NOCUENTA)
);

