create or replace
TRIGGER "INICIARCREDITO"
BEFORE INSERT ON CUENTA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE

BEGIN
	IF :NEW.TIPOCUENTE=1 THEN

    :NEW.LIMCREDITO :=5000;

	ELSIF :NEW.TIPOCUENTE =2 THEN
  	:NEW.LIMCREDITO :=15000;


	ELSIF :NEW.TIPOCUENTE = 3 THEN
		:NEW.LIMCREDITO:=5000;

	ELSIF :NEW.TIPOCUENTE=4 THEN
			:NEW.LIMCREDITO :=25000;

	END IF;
END;

create or replace
TRIGGER "TRANSACCION"
AFTER INSERT ON TRANSACCION
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
SALDOACT1 NUMBER;
SALDOACT2 NUMBER;

BEGIN

	SELECT SALDO INTO SALDOACT1 FROM CUENTA WHERE NOCUENTA = :NEW.NOCUENTA1;

	IF :NEW.TIPOTRANSACCION=1 THEN

	UPDATE CUENTA SET SALDO = SALDOACT1+:NEW.CANTIDAD WHERE NOCUENTA=:NEW.NOCUENTA1;

	ELSIF :NEW.TIPOTRANSACCION=2 THEN
	UPDATE CUENTA SET SALDO=SALDOACT1-:NEW.CANTIDAD WHERE NOCUENTA=:NEW.NOCUENTA1;

	ELSIF :NEW.TIPOTRANSACCION=3 THEN
	UPDATE CUENTA SET SALDO=SALDOACT1-:NEW.CANTIDAD WHERE NOCUENTA=:NEW.NOCUENTA1;


	ELSIF :NEW.TIPOTRANSACCION=4 THEN
			SELECT SALDO INTO SALDOACT2 FROM CUENTA WHERE NOCUENTA=:NEW.NOCUENTA2;
			UPDATE CUENTA SET SALDO=SALDOACT1-:NEW.CANTIDAD WHERE NOCUENTA=:NEW.NOCUENTA1;
			UPDATE CUENTA SET SALDO=SALDOACT2+:NEW.CANTIDAD WHERE NOCUENTA=:NEW.NOCUENTA2;			


	END IF;
END;